### ISSUE TITLE
Ordering Information Confusing

### ISSUE THREAD

**Issue by flywire** [LibreSolar/libresolar.github.io#10]
Ordering is not accessible. The current process requires software download of over a gigabyte, install many gigabytes and translate instructions for old KiCAD version to current version.

Despite some acceptance of accept native KiCAD board files (extension .kicad_pcb), Gerber is the industry default.

Preferably provide:
1. Default supplier for devices
1. Gerber and BOM files for each device (so even other suppliers could grab them easily)
1. As a minimum, update [Ordering - KiCAD Gerber export](https://github.com/LibreSolar/libresolar.github.io/blob/master/_docs/2b_pcb_ordering.md#kicad-gerber-export) instructions to current KiCAD (V5.1)

**Comment by flywire** [comment]
In KiCAD V5.1:
1. Open Existing Project *.pro
1. Click on PCB Layout Editor icon or in the folder list
1. Click Board Setup on the toolbar, Design Rules, Solder Mask/Paste, and confirm all values set to zero.

...

**Comment by martinjaeger** [comment]
You are right, the instruction should be updated to most recent KiCad version.

The reason I don't provide the Gerber files and BOM in the repository:
- It's easy to get a mismatch between native PCB files and the Gerber/BOM files if you change something in the PCB and forget to update all production files aswell.
- They bloat the size of the repository and contain sort of redundant information.

The only solution for this problem would be auto-generated BOMs and Gerber files each time a new commit is pushed to the server, similar as it is done with Doxygen for the software. This might even be possible with Travis CI, but I didn't try that out yet.

There is no default supplier. Most parts should be available on digikey, mouser, farnell, etc.. I won't place a sort of advertisement on the website for one of them. For PCBs I generally like [Aisler](https://aisler.net), but they don't offer 70um copper thickness, which is not ideal for the higher power 20A board or the BMS boards.

**Comment by flywire** [comment]
KiCAD V5.1 issues are ongoing with BOM.
Schematic Layout Editor Project Rescue Helper reports:
>This schematic was made using older symbol libraries which may break the schematic. ...

Seems KiBoM plugin install has not been updated to KiCAD V5.1 either.

**Comment by martinjaeger** [comment]
These docs are not part of the website anymore, but integrated into the learn.libre.solar website.
