### ISSUE TITLE
Add Reddit community to the footer FOLLOW section...

### ISSUE THREAD

**Issue by mark-stopka** [LibreSolar/libresolar.github.io#4]
I've created a [Reddit community](https://www.reddit.com/r/LibreSolar/) for Libre Solar project, and I would like you to link it in the FOLLOW part of the website footer. You can use official Reddit logo as per [usage guidelines described on the Reddit website](https://www.reddit.com/wiki/licensing).

**Comment by martinjaeger** [comment]
Done that right now. Thanks for the idea :)
