### ISSUE TITLE
Place libre.solar behind CloudFlare proxy or use Let's encrypt to provide TLS connectivity

### ISSUE THREAD

**Issue by mark-stopka** [LibreSolar/libresolar.github.io#6]
I am not sure how github.io pages work exactly, but Google and other search-engines alike are penalizing non-TLS websites in their search results; it would be beneficial to either install Let's encrypt certificate to provide HTTPS version of the website or place the http://libre.solar website behind a CloudFlare proxy to get native HTTPS connectivity to improve the search ratings of the website.

In addition, I think Google Analytics and Facebook Pixel tracking should be added to the website, so we get insight into our potential user-base.

**Comment by martinjaeger** [comment]
Issue resolved using native github pages TLS support.
